version: '3.8'

services:

  server1:
    build: .
    container_name: server1
    ports:
      - "8081:80"
    volumes:
      - ./server1:/var/www/html

  server2:
    build: .
    container_name: server2
    ports:
      - "8082:80"
    volumes:
      - ./server2:/var/www/html